# Generated by Django 5.1.5 on 2025-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=202)),
                ('image', models.ImageField(upload_to='about/')),
                ('username', models.CharField(max_length=202)),
                ('telegram', models.CharField(max_length=202)),
                ('instagram', models.CharField(max_length=202)),
                ('linkedin', models.CharField(max_length=202)),
                ('github', models.CharField(max_length=202)),
                ('facebook', models.CharField(max_length=202)),
                ('twitter', models.CharField(max_length=202)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=202)),
                ('title', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=202)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=202)),
                ('title', models.CharField(max_length=202)),
                ('job', models.CharField(max_length=202)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
