# Generated by Django 5.1.5 on 2025-01-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding', models.CharField(max_length=202)),
                ('title', models.CharField(max_length=202)),
                ('link', models.CharField(max_length=202)),
                ('image', models.ImageField(upload_to='work/')),
                ('about', models.TextField()),
                ('period', models.CharField(max_length=202)),
                ('client', models.CharField(max_length=202)),
                ('services', models.CharField(max_length=202)),
                ('project', models.CharField(max_length=202)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='work.work')),
            ],
        ),
    ]
